
POST http://localhost:3000/dogs/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUyOTYzODh9.sySRh4j1Dt0UbhIOo0M2OXHPGvNODyPElpR64VQQuHc
Content-Type: application/json

{
  "name" : "karabas",
  "age" : 2,
  "breed" : "K9"
}


###

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Matthew",
  "email": "matthew@info.com",
  "password": "password",
  "password_confirmation": "password"
}

###

POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "matthew@info.com",
  "password": "password"
}