
POST http://localhost:3000/dogs/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzUyOTkyNDR9.Er-ixDLLSRW1H4unhcOd5_YMQXGR3LCzOk3r2XwPkVM
Content-Type: application/json

{
  "name" : "Braveheart",
  "age" : 4,
  "breed" : "retriever"
}


###

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Kyle Walker",
  "email": "walker@info.com",
  "password": "password",
  "password_confirmation": "password"
}

###

POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "walker@info.com",
  "password": "password"
}